visibility: hidden
authors:
  - name: Laura Marcos
project_urls:
    Project Site: https://github.com/chanzuckerberg/napari-demo
    Report Issues: https://github.com/chanzuckerberg/napari-demo/issues
    Documentation: https://github.com/chanzuckerberg/napari-demo
    User Support: https://forum.image.sc
    Twitter: https://twitter.com/cziscience
