visibility: hidden
authors:
  - name: Ziyang Liu
    email: zliu@chanzuckerberg.com
  - name: Laura Marcos
    orcid: 0000-0002-4638-7015
project_urls:
    Twitter: https://twitter.com/cziscience
    Report Issues: https://github.com/chanzuckerberg/napari-demo/issues,
    Documentation: https://github.com/chanzuckerberg/napari-demo,
    User Support: https://forum.image.sc
